=== cato-/otfbot/xml-config/chatbot-config.dtd
<!ELEMENT chatbot (general, (network)+)>

<!ELEMENT general ((modul)*, nickname, realname, (operator)*)>

<!ELEMENT modul (param)*>
<!ATTLIST modul
	name	CDATA #REQUIRED
>
<!ELEMENT param EMPTY>
<!ATTLIST param
	name	CDATA #REQUIRED
	value	CDATA #REQUIRED
>

<!ELEMENT nickname (#PCDATA)>
<!ELEMENT realname (#PCDATA)>

<!ELEMENT operator (nick,auth,level)>
<!ELEMENT nick (#PCDATA)>
<!ELEMENT auth (#PCDATA | nickserv)>
<!ELEMENT level (#PCDATA)>

<!ELEMENT network (server, port, nickname, nickserv-pwd, (channel)+)>
<!ATTLIST network
	name CDATA #REQUIRED
>

<!ELEMENT server (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT nickserv-pwd (#PCDATA)>
<!ELEMENT channel (modul)*>

=== cato-/otfbot/xml-config/config.xml
<?xml version="1.0"?>
<!DOCTYPE chatbot-config SYSTEM "chatbot-config.dtd">
<chatbot>
	<general>
		<modul name="generalMod">
			<param name="paraname" value="paravalue" />
		</modul>
		<modul name="answerMod" />
		<modul name="commandsMod" />
		<modul name="logMod" />
		<modul name="rdfMod">
			<param name="wait" value="10" />
		</modul>
		<nickname>chatBot</nickname>
		<realname>der chattende Bot</realname>
		<operator>
			<nick>allo</nick>
			<auth>nickserv</auth>
			<level>0</level>
		</operator>
		<operator>
			<nick>cato</nick>
		</operator>
	</general>
	<network name="netzwerk1">
		<server>bots.somenetwork.net</server>
		<port>6667</port>
		<nickname>einnick</nickname>
		<channel name="#channel1">
			<modul name="identifyMod">
				<param name="password" value="pwd" />
			</modul>
			<modul name="logMod">
				<enable>False</enable>
			</modul>
			<modul name="rdfMod">
				<param name="feed" value="http://www.heise.de/newsticker/heise.rdf" />
				<param name="feed" value="http://some.net/other.rdf" />
			</modul>
		</channel>	
		<channel name="#channel2" />
	</network>
	<network name="freenode">
		<server>irc.freenode.net</server>
		<port>6667</port>
		<nickname>ubot</nickname>
		<channel name="#yacy">
			<modul name="identifyMod">
				<param name="password" value="pwd" />
			</modul>
			<modul name="logMod">
				<enable>False</enable>
			</modul>
		</channel>
	</network>
</chatbot>
